apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-deployment
  labels:
    app: template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: template
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
      - name: template
        image: ghcr.io/lukaj-master/demo3-app:sha-87482f4b19af1542293a29ae36eb2afdf5c6f000
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 12
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 3
