name: Publish and deploy microservice

on:
  push:
    branches: ['master']
    paths:
    - 'TemplateApp/**'
    - 'TemplateApp.sln'
    - '.github/workflows/pipeline.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-app
  DOCKERFILE_DIR: TemplateApp
  DEPLOYMENT_PATH: k8s-resources/deployment.yaml

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image_digest: ${{ steps.build-push.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      
  trigger-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        persist-credentials: false
    - name: Update version in deployment manifest
      run: |
          sed -i 's#image: ${{ env.REGISTRY }}.*#image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}#' ${{ env.DEPLOYMENT_PATH }}
    - name: Commit files
      run: |
          git config user.name "GitHub CI Runner"
          git config user.email "gh-ci-runner@rs2.luka-j.rocks"
          git commit -am "[CI] Deploy ${{ github.sha }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true

